version: "3"
services:
    cep:
        container_name: onyo-cep
        build:
            context: .
            dockerfile: Dockerfile.cep
        image: registry.heroku.com/onyo-cep/web
        stdin_open: true
        tty: true
        ports:
            - "8001:8001"
        environment:
            PORT: "8001"
            DJANGO_CONFIGURATION: Development
    funcionario:
        container_name: onyo-funcionario
        build:
            context: .
            dockerfile: Dockerfile.funcionario
        image: registry.heroku.com/onyo-funcionario/web
        stdin_open: true
        tty: true
        ports:
            - "8002:8002"
        environment:
            PORT: "8002"
            DJANGO_CONFIGURATION: Development
            CEP_URL: http://localhost:8001/api/v1/ceps/
