# Generated by Django 2.1.4 on 2018-12-07 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('cep', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('logradouro', models.CharField(max_length=200)),
                ('bairro', models.CharField(max_length=200)),
                ('localidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
    ]
